### ISSUE TITLE
Как да разберем, кои глави са вече в процес на превод

### ISSUE THREAD

**Issue by adrianhr91** [kberov/progit2-bg#1]
Би ми било интересно да се опитам да преведа някои от главите на книгата, но как да знам, че някой друг вече не превежда същата глава? Доста кофти би било 2ма (или повече) човека да вършат една и съща работа без да осъзнават.

Като просто решение на проблема бих предложил за всяка глава да се създаде issue. Който работи по преведа може да се assigne-не към него. (Трябва да поработя по превода на български). След приключване на работа и merge на pull-request issue-то се затваря.

**Comment by kberov** [comment]
Подробностите са описани в https://github.com/kberov/progit2-bg/blob/master/TRANSLATION_NOTES.asc
Ако съм забравил нещо добавяйте и предлагайте.
Поздрави!

**Comment by kberov** [comment]
А в README съм написал.


„За да се знае, че сте започнали работа, създайте задача в https://github.com/kberov/progit2-bg/issues. Опишете в нея каква част ще преведете и започнете работа. В задачата ще обсъждате работата по нея.“

**Comment by kberov** [comment]
Моля обаче първо прочетете преведеното дотук, за да продължим в горе-долу същия стил
