### ISSUE TITLE
Леки корекции по progit2-bg/TRANSLATION_NOTES.asc

### ISSUE THREAD

**Issue by Hrissimir** [kberov/progit2-bg#2]
Някои от термините не са преведени правилно или липсва добър пример.
Когато читателят полага основите на знанията тези неща са от изключителна важност.

**Comment by Hrissimir** [comment]
- |fetch| ...
+|fetch|донасям|Fetch URL – Адрес, от който да вземем данните/информацията

**Comment by hrissimir** [comment]
Подкрепям каузата книгата да бъде преведена , но...
За да има практическа стойност, този превод трябва да бъде направен в консистентен стил насочен към напълно незапознатите с материята. 
Идеята да изхвърлим всички чуждици и да използваме българските им еквиваленти при книга от този калибър (според мен) е просто абсурдна. 
Бил съм свидетел на подобно отношение към чуждиците в роден ВУЗ и в последствие това рефлектира неблагоприятно върху знанията на студентите и способноста им да надграждат вече добитите  такива. 
Имаше случаи в които 50% от потока (хора доста по-напред с матеряла, който са чели на английски) не могат да разберат условието на изпита само защото е зададено на български и то с грешно преведени термини.
Не споделям виждането на създателя на репото и по-скоро бих я превел цялата сам.
Това е последната ми интеракця с репото.

**Comment by kberov** [comment]
Знам. Написал съм в този документ, че винагии като въвеждме ново понятие, слагамае английската дума в скоби и после ползваме българската. Така няма да се объркват. Прочети преведеното дотук и направи каквито промени смят ш за нужни. Можеш да направиш "пул рикуест" (или заявка за сливане?). Кое то говори повече на пръв поглед?

**Comment by Hrissimir** [comment]
Опитах, но нямам права. Мисля че е нещо по настройките за репото и контрибютърите.

**Comment by kberov** [comment]
Естествено, че нямате права. Направете си копие на проекта в гитхъб, променете каквото смятатате, че трябва да се промени и направете заявка за сливане.
Вижте https://guides.github.com/activities/forking/

**Comment by Hrissimir** [comment]
Благодаря !
