### ISSUE TITLE
Превод на 6-та глава

### ISSUE THREAD

**Issue by karinakozarova** [kberov/progit2-bg#3]
Ще започна превод на глава 6 - гитхъб.

**Comment by kberov** [comment]
Благодаря, Карина!
Моля уверете се, че сте прочели README.asc и връзките в него.
Начинът на съвместна работа ще бъде този: https://guides.github.com/activities/forking/.
Моля, не се колебайте да направите заявка за сливане скоро, независимо колко сте превели, за да можем да изчистваме постепенно проблемите.
