### ISSUE TITLE
Линкове към снимките

### ISSUE THREAD

**Issue by karinakozarova** [kberov/progit2-bg#4]
Доколкото забелязах, линковете към снимките не излизат в нито един от файловете.

**Comment by kberov** [comment]
Излизат. Изпълни ли `asciidoctor progit.asc`?
Пример:
http://i-can.eu/progit2-bg/progit.html#_За_управлението_на_версии

**Comment by kberov** [comment]
Махна ли коментара пред шеста глава?
https://raw.githubusercontent.com/kberov/progit2-bg/master/progit.asc

**Comment by karinakozarova** [comment]
Не бях маханал коментарите, моя грешка. Съжалявам.
